
#define WINDOW_CLASS_NAME L"SampleWindow"
#define MAIN_WINDOW_TITLE L"CastleVania"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0,0,0)
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define BOARD_HEIGHT 60


#define MAX_FRAME_RATE 120

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_MAP_1 1000
#define ID_TEX_MAP_2 2000
#define ID_TEX_MAP_3 3000
#define ID_TEX_SIMON 30
#define ID_TEX_CANDLE 2
#define ID_TEX_ITEM 1
#define ID_TEX_HIDDEN 5
#define ID_TEX_ENEMY 3






#define TILE_MAP_SIZE 500


// TYPE OBJECT
#define TYPE_OBJECT_HIDDEN 0
#define TYPE_OBJECT_ENEMY 1
#define TYPE_OBJECT_GROUND 2
#define TYPE_OBJECT_PLAYER 3
#define TYPE_OBJECT_WEAPON 4
#define TYPE_OBJECT_BACKGROUND 5
#define TYPE_OBJECT_ITEM 6


//SIMON CONSTANTS
#define OFFSET_FLIP_X 24

#define CAM_Y_DEFAULT_STAGE_1 10.0f
#define CAM_Y_DEFAULT_STAGE_2 25.0f

#define NUMBER_OF_CANDLE 5
#define NUMBER_OF_BRICK 300

#define Y_BASE 167
#define DISTANCE_BETWEEN_CANDLE 110

//SCENE GAME
#define SCENE_GAME_ID 100