
#define WINDOW_CLASS_NAME L"SampleWindow"
#define MAIN_WINDOW_TITLE L"CastleVania"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0,0,0)
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define BOARD_HEIGHT 60


#define MAX_FRAME_RATE 120

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_MAP 1000
#define ID_TEX_SIMON 30
#define ID_TEX_CANDLE 50



#define TILE_MAP_SIZE 500